### ISSUE TITLE
Error when extracting field tags on Relay::Node type - owner evaluates to nil

### ISSUE THREAD

**Issue by dhendrie91** [yabeda-rb/yabeda-graphql#1]
When `extract_field_tags` is called with a `GraphQL::Types::Relay::Node` type the field owner evaluates to `nil`

top of stack trace:
```
undefined method `graphql_name' for nil:NilClass
/home/daniel/.rvm/gems/ruby-2.6.5/gems/yabeda-graphql-0.2.0/lib/yabeda/graphql/tracing.rb:60:in `extract_field_tags'
/home/daniel/.rvm/gems/ruby-2.6.5/gems/yabeda-graphql-0.2.0/lib/yabeda/graphql/tracing.rb:29:in `platform_trace'
```

This only appears to happen with those specific node types from what I can tell, the Node type doesn't respond to either `#owner` or `#metadata` and as a result the owner evaluates as nil and the method fails.

` owner = field.respond_to?(:owner) ? field.owner : field.metadata[:type_class].owner`

I think this can maybe be fixed by changing the owner to evaluate as `field.type_class` instead

encountered on 

Ruby v2.6.5 
Rails v6.0.3.2
Ruby GraphQL v1.11.5

I'd be happy to submit a PR if i had some guidance on this as I'm not overly familiar with the internals of the GraphQL gem.

**Comment by Envek** [comment]
Hi! Unfortunately I can't guide you at the moment, but will be absolutely happy to get pull request with the fix!

You can start from my colleague's talk about GraphQL-Ruby internals: [GraphQL-Ruby under the hood](https://speakerdeck.com/dmitrytsepelev/chto-skryvaiet-pod-kapotom-graphql-ruby-i-kak-eto-pomoghaiet-pisat-bolieie-elieghantnyi-api) (start from slide [20](https://speakerdeck.com/dmitrytsepelev/chto-skryvaiet-pod-kapotom-graphql-ruby-i-kak-eto-pomoghaiet-pisat-bolieie-elieghantnyi-api?slide=20))

**Comment by dhendrie91** [comment]
Thanks for this, I've since discovered that i don't think this is actually a bug with this gem. Ruby graphql doesnt expose the owner on node field types by default if using `add_field(GraphQL::Types::Relay::NodeField)` as suggested in the docs here https://github.com/rmosolgo/graphql-ruby/blob/master/guides/relay/object_identification.md however if you use your own implementation as shown here https://github.com/rmosolgo/graphql-ruby/blob/57a0ee9ded8270438f72070c3bc0d725f18bc4f6/lib/graphql/types/relay/node_field.rb#L13

like so :
```
    field :node, GraphQL::Types::Relay::Node, null: true, extras: [:owner],
          description: "Fetches an object given its ID" do
      argument :id, ID, required: true
    end

    def node(id:, owner:)
      context.schema.object_from_id(id, context)
    end
```
You can specify the owners extra and the yabeda-graphql gem then works as expected
(you can do the same thing for the node**s** field as well)

Just posting here in case others find this useful :smile:
